version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  feed_fetcher:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: python fetch_feeds.py
    volumes:
      - ./api:/app
      - ./feeds.yml:/app/feeds.yml
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant

volumes:
  qdrant_data: 